/* SPDX-FileCopyrightText: © 2023-2025 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    RAB_DEF_OPERAND(r3000gte, sf, EncodedFieldMask::r3000gte_sf, (u8))
    RAB_DEF_OPERAND(r3000gte, mx, EncodedFieldMask::r3000gte_mx, (u8))
    RAB_DEF_OPERAND(r3000gte, v, EncodedFieldMask::r3000gte_v, (u8))
    RAB_DEF_OPERAND(r3000gte, cv, EncodedFieldMask::r3000gte_cv, (u8))
    RAB_DEF_OPERAND(r3000gte, lm, EncodedFieldMask::r3000gte_lm, (u8))
