/* SPDX-FileCopyrightText: © 2023-2024 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    RAB_DEF_OPERAND(r3000gte, sf, EncodedFieldMask::r3000gte_sf)
    RAB_DEF_OPERAND(r3000gte, mx, EncodedFieldMask::r3000gte_mx)
    RAB_DEF_OPERAND(r3000gte, v, EncodedFieldMask::r3000gte_v)
    RAB_DEF_OPERAND(r3000gte, cv, EncodedFieldMask::r3000gte_cv)
    RAB_DEF_OPERAND(r3000gte, lm, EncodedFieldMask::r3000gte_lm)
