/* SPDX-FileCopyrightText: © 2024 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    RAB_DEF_OPERAND(r4000allegrex, s_vs)
    RAB_DEF_OPERAND(r4000allegrex, s_vt)
    RAB_DEF_OPERAND(r4000allegrex, s_vd)
    RAB_DEF_OPERAND(r4000allegrex, s_vt_imm)
    RAB_DEF_OPERAND(r4000allegrex, s_vd_imm)

    RAB_DEF_OPERAND(r4000allegrex, vt_6)

    RAB_DEF_OPERAND(r4000allegrex, pos)
    RAB_DEF_OPERAND(r4000allegrex, size)
    RAB_DEF_OPERAND(r4000allegrex, size_plus_pos)

    RAB_DEF_OPERAND(r4000allegrex, imm3)

    // RAB_DEF_OPERAND(r4000allegrex, offset14)
    RAB_DEF_OPERAND(r4000allegrex, offset14_base)
    RAB_DEF_OPERAND(r4000allegrex, offset14_base_maybe_wb)
