/* SPDX-FileCopyrightText: © 2022-2025 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    #include "r5900ee/r5900ee_normal.inc"
    #include "r5900ee/r5900ee_special.inc"
    #include "r5900ee/r5900ee_regimm.inc"

    #include "r5900ee/r5900ee_mmi.inc"
    #include "r5900ee/r5900ee_mmi_0.inc"
    #include "r5900ee/r5900ee_mmi_1.inc"
    #include "r5900ee/r5900ee_mmi_2.inc"
    #include "r5900ee/r5900ee_mmi_3.inc"
    #include "r5900ee/r5900ee_mmi_pmfhl.inc"
    #include "r5900ee/r5900ee_mmi_pmthl.inc"

    #include "r5900ee/r5900ee_cop0.inc"
    #include "r5900ee/r5900ee_cop0_tlb.inc"

    #include "r5900ee/r5900ee_cop1.inc"
    #include "r5900ee/r5900ee_cop1_fpu_s.inc"

    #include "r5900ee/r5900ee_cop2.inc"
    #include "r5900ee/r5900ee_cop2_bc2.inc"
    #include "r5900ee/r5900ee_cop2_special1.inc"
    #include "r5900ee/r5900ee_cop2_special2.inc"
    #include "r5900ee/r5900ee_cop2_viwr.inc"
