/* SPDX-FileCopyrightText: © 2022-2025 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    #include "r5900/r5900_normal.inc"
    #include "r5900/r5900_special.inc"
    #include "r5900/r5900_regimm.inc"

    #include "r5900/r5900_mmi.inc"
    #include "r5900/r5900_mmi_0.inc"
    #include "r5900/r5900_mmi_1.inc"
    #include "r5900/r5900_mmi_2.inc"
    #include "r5900/r5900_mmi_3.inc"
    #include "r5900/r5900_mmi_pmfhl.inc"
    #include "r5900/r5900_mmi_pmthl.inc"

    #include "r5900/r5900_cop0.inc"
    #include "r5900/r5900_cop0_tlb.inc"

    #include "r5900/r5900_cop1.inc"
    #include "r5900/r5900_cop1_fpu_s.inc"

    #include "r5900/r5900_cop2.inc"
    #include "r5900/r5900_cop2_bc2.inc"
    #include "r5900/r5900_cop2_special1.inc"
    #include "r5900/r5900_cop2_special2.inc"
    #include "r5900/r5900_cop2_viwr.inc"
