/* SPDX-FileCopyrightText: © 2022-2025 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    // RSP instructions

    #include "rsp/rsp_cop2.inc"
    #include "rsp/rsp_cop2_vu.inc"

    #include "rsp/rsp_normal_lwc2.inc"
    #include "rsp/rsp_normal_swc2.inc"

    #include "rsp/rsp_normal.inc"
    #include "rsp/rsp_special.inc"
    #include "rsp/rsp_regimm.inc"
    #include "rsp/rsp_cop0.inc"
