/* SPDX-FileCopyrightText: © 2022-2025 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    #include "core/core_normal.inc"
    #include "core/core_special.inc"
    #include "core/core_regimm.inc"

    #include "core/core_cop0.inc"
    #include "core/core_cop0_bc0.inc"
    #include "core/core_cop0_tlb.inc"

    #include "core/core_cop1.inc"
    #include "core/core_cop1_bc1.inc"
    #include "core/core_cop1_fpu_s.inc"
    #include "core/core_cop1_fpu_d.inc"
    #include "core/core_cop1_fpu_w.inc"
    #include "core/core_cop1_fpu_l.inc"

    #include "core/core_cop2.inc"
