/* SPDX-FileCopyrightText: © 2024 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    RAB_DEF_OPCODE_REDIRECT(0x10, r3000gte, coprocessor2_gte)
    RAB_DEF_OPCODE_REDIRECT(0x11, r3000gte, coprocessor2_gte)
    RAB_DEF_OPCODE_REDIRECT(0x12, r3000gte, coprocessor2_gte)
    RAB_DEF_OPCODE_REDIRECT(0x13, r3000gte, coprocessor2_gte)
    RAB_DEF_OPCODE_REDIRECT(0x14, r3000gte, coprocessor2_gte)
    RAB_DEF_OPCODE_REDIRECT(0x15, r3000gte, coprocessor2_gte)
    RAB_DEF_OPCODE_REDIRECT(0x16, r3000gte, coprocessor2_gte)
    RAB_DEF_OPCODE_REDIRECT(0x17, r3000gte, coprocessor2_gte)
    RAB_DEF_OPCODE_REDIRECT(0x18, r3000gte, coprocessor2_gte)
    RAB_DEF_OPCODE_REDIRECT(0x19, r3000gte, coprocessor2_gte)
    RAB_DEF_OPCODE_REDIRECT(0x1A, r3000gte, coprocessor2_gte)
    RAB_DEF_OPCODE_REDIRECT(0x1B, r3000gte, coprocessor2_gte)
    RAB_DEF_OPCODE_REDIRECT(0x1C, r3000gte, coprocessor2_gte)
    RAB_DEF_OPCODE_REDIRECT(0x1D, r3000gte, coprocessor2_gte)
    RAB_DEF_OPCODE_REDIRECT(_, none, coprocessor2)
