/* SPDX-FileCopyrightText: © 2024 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    #include "r4000allegrex/r4000allegrex_normal.inc"

    #include "r4000allegrex/r4000allegrex_special.inc"
    #include "r4000allegrex/r4000allegrex_special_rs.inc"
    #include "r4000allegrex/r4000allegrex_special_sa.inc"

    #include "r4000allegrex/r4000allegrex_regimm.inc"

    #include "r4000allegrex/r4000allegrex_special2.inc"

    #include "r4000allegrex/r4000allegrex_special3.inc"
    #include "r4000allegrex/r4000allegrex_special3_bshfl.inc"

    #include "r4000allegrex/r4000allegrex_cop0.inc"
    #include "r4000allegrex/r4000allegrex_cop0_bc0.inc"
    #include "r4000allegrex/r4000allegrex_cop0_tlb.inc"

    #include "r4000allegrex/r4000allegrex_cop1.inc"
    #include "r4000allegrex/r4000allegrex_cop1_bc1.inc"
    #include "r4000allegrex/r4000allegrex_cop1_fpu_s.inc"
    #include "r4000allegrex/r4000allegrex_cop1_fpu_w.inc"

    #include "r4000allegrex/r4000allegrex_cop2.inc"
    #include "r4000allegrex/r4000allegrex_cop2_bc2.inc"
    #include "r4000allegrex/r4000allegrex_cop2_mfhc2.inc"
    #include "r4000allegrex/r4000allegrex_cop2_mfhc2_p.inc"
    #include "r4000allegrex/r4000allegrex_cop2_mfhc2_p_s.inc"
    #include "r4000allegrex/r4000allegrex_cop2_mthc2.inc"

    #include "r4000allegrex/r4000allegrex_vfpu0.inc"
    #include "r4000allegrex/r4000allegrex_vfpu1.inc"
    #include "r4000allegrex/r4000allegrex_vfpu3.inc"

    #include "r4000allegrex/r4000allegrex_vfpu4.inc"
    #include "r4000allegrex/r4000allegrex_vfpu4_fmt0.inc"
    #include "r4000allegrex/r4000allegrex_vfpu4_fmt0_fmt0.inc"
    #include "r4000allegrex/r4000allegrex_vfpu4_fmt0_fmt2.inc"
    #include "r4000allegrex/r4000allegrex_vfpu4_fmt0_fmt3.inc"
    #include "r4000allegrex/r4000allegrex_vfpu4_fmt0_rnd.inc"
    #include "r4000allegrex/r4000allegrex_vfpu4_fmt0_cvtflt.inc"
    #include "r4000allegrex/r4000allegrex_vfpu4_fmt0_cvtint.inc"
    #include "r4000allegrex/r4000allegrex_vfpu4_fmt0_fmt8.inc"
    #include "r4000allegrex/r4000allegrex_vfpu4_fmt0_fmt9.inc"
    #include "r4000allegrex/r4000allegrex_vfpu4_fmt0_control.inc"
    #include "r4000allegrex/r4000allegrex_vfpu4_fmt0_color.inc"
    #include "r4000allegrex/r4000allegrex_vfpu4_fmt0_cst.inc"
    #include "r4000allegrex/r4000allegrex_vfpu4_fmt2.inc"
    #include "r4000allegrex/r4000allegrex_vfpu4_fmt2_cndmove.inc"

    #include "r4000allegrex/r4000allegrex_vfpu5.inc"

    #include "r4000allegrex/r4000allegrex_vfpu6.inc"
    #include "r4000allegrex/r4000allegrex_vfpu6_fmt7.inc"
    #include "r4000allegrex/r4000allegrex_vfpu6_fmt7_fmt0.inc"

    #include "r4000allegrex/r4000allegrex_vfpu7.inc"

    #include "r4000allegrex/r4000allegrex_quadlr.inc"
