/* SPDX-FileCopyrightText: © 2022-2024 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    #include "cpu/cpu_normal.inc"
    #include "cpu/cpu_special.inc"
    #include "cpu/cpu_regimm.inc"

    #include "cpu/cpu_cop0.inc"
    #include "cpu/cpu_cop0_bc0.inc"
    #include "cpu/cpu_cop0_tlb.inc"

    #include "cpu/cpu_cop1.inc"
    #include "cpu/cpu_cop1_bc1.inc"
    #include "cpu/cpu_cop1_fpu_s.inc"
    #include "cpu/cpu_cop1_fpu_d.inc"
    #include "cpu/cpu_cop1_fpu_w.inc"
    #include "cpu/cpu_cop1_fpu_l.inc"

    #include "cpu/cpu_cop2.inc"
