/* SPDX-FileCopyrightText: © 2022-2024 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    RABBITIZER_DEF_REG(
        R5900_VF,  vf0,  vf0,
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf1,  vf1,
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf2,  vf2,
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf3,  vf3,
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf4,  vf4,
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf5,  vf5,
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf6,  vf6,
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf7,  vf7,
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf8,  vf8,
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf9,  vf9,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf10, vf10,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf11, vf11,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf12, vf12,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf13, vf13,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf14, vf14,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf15, vf15,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf16, vf16,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf17, vf17,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf18, vf18,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf19, vf19,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf20, vf20,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf21, vf21,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf22, vf22,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf23, vf23,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf24, vf24,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf25, vf25,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf26, vf26,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf27, vf27,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf28, vf28,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf29, vf29,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf30, vf30,
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf31, vf31,
    )
