/* SPDX-FileCopyrightText: © 2022-2024 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    RABBITIZER_DEF_REG(
        R5900_VI,  vi0,  vi0,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi1,  vi1,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi2,  vi2,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi3,  vi3,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi4,  vi4,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi5,  vi5,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi6,  vi6,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi7,  vi7,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi8,  vi8,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi9,  vi9,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi10, vi10,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi11, vi11,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi12, vi12,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi13, vi13,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi14, vi14,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi15, vi15,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi16, vi16,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi17, vi17,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi18, vi18,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi19, vi19,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi20, vi20,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi21, vi21,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi22, vi22,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi23, vi23,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi24, vi24,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi25, vi25,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi26, vi26,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi27, vi27,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi28, vi28,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi29, vi29,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi30, vi30,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi31, vi31,
        0
    )
