/* SPDX-FileCopyrightText: © 2024-2025 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    // Always false
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, fl,  0, )
    // Equal
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, eq,  1, )
    // Less than
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, lt,  2, )
    // Less than or equal
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, le,  3, )
    // Always true
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, tr,  4, )
    // Not equal
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, ne,  5, )
    // Greater than or equal
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, ge,  6, )
    // Greater than
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, gt,  7, )
    // Equal to zero
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, ez,  8, )
    // Equal to NaN
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, en,  9, )
    // Absolute value equal to infinity
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, ei, 10, )
    // Equal to infinity or NaN
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, es, 11, )
    // Not equal to zero
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, nz, 12, )
    // Not equal to NaN
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, nn, 13, )
    // Absolute value not equal to infinity
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, ni, 14, )
    // Not equal to infinity and not equal to NaN
    RABBITIZER_DEF_REG_NODOLLAR(R4000ALLEGREX_VCOND, ns, 15, )
