/* SPDX-FileCopyrightText: © 2022-2024 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    RABBITIZER_DEF_REG(
        fv0,   0,
        name_n32: Some("$fv0"),
        name_n64: Some("$fv0"),
    )
    RABBITIZER_DEF_REG(
        fv0f,  1,
        name_n32: Some("$ft14"),
        name_n64: Some("$ft12"),
    )
    RABBITIZER_DEF_REG(
        fv1,   2,
        name_n32: Some("$fv1"),
        name_n64: Some("$fv1"),
    )
    RABBITIZER_DEF_REG(
        fv1f,  3,
        name_n32: Some("$ft15"),
        name_n64: Some("$ft13"),
    )
    RABBITIZER_DEF_REG(
        ft0,   4,
        name_n32: Some("$ft0"),
        name_n64: Some("$ft0"),
    )
    RABBITIZER_DEF_REG(
        ft0f,  5,
        name_n32: Some("$ft1"),
        name_n64: Some("$ft1"),
    )
    RABBITIZER_DEF_REG(
        ft1,   6,
        name_n32: Some("$ft2"),
        name_n64: Some("$ft2"),
    )
    RABBITIZER_DEF_REG(
        ft1f,  7,
        name_n32: Some("$ft3"),
        name_n64: Some("$ft3"),
    )
    RABBITIZER_DEF_REG(
        ft2,   8,
        name_n32: Some("$ft4"),
        name_n64: Some("$ft4"),
    )
    RABBITIZER_DEF_REG(
        ft2f,  9,
        name_n32: Some("$ft5"),
        name_n64: Some("$ft5"),
    )
    RABBITIZER_DEF_REG(
        ft3,  10,
        name_n32: Some("$ft6"),
        name_n64: Some("$ft6"),
    )
    RABBITIZER_DEF_REG(
        ft3f, 11,
        name_n32: Some("$ft7"),
        name_n64: Some("$ft7"),
    )
    RABBITIZER_DEF_REG(
        fa0,  12,
        name_n32: Some("$fa0"),
        name_n64: Some("$fa0"),
    )
    RABBITIZER_DEF_REG(
        fa0f, 13,
        name_n32: Some("$fa1"),
        name_n64: Some("$fa1"),
    )
    RABBITIZER_DEF_REG(
        fa1,  14,
        name_n32: Some("$fa2"),
        name_n64: Some("$fa2"),
    )
    RABBITIZER_DEF_REG(
        fa1f, 15,
        name_n32: Some("$fa3"),
        name_n64: Some("$fa3"),
    )
    RABBITIZER_DEF_REG(
        ft4,  16,
        name_n32: Some("$fa4"),
        name_n64: Some("$fa4"),
    )
    RABBITIZER_DEF_REG(
        ft4f, 17,
        name_n32: Some("$fa5"),
        name_n64: Some("$fa5"),
    )
    RABBITIZER_DEF_REG(
        ft5,  18,
        name_n32: Some("$fa6"),
        name_n64: Some("$fa6"),
    )
    RABBITIZER_DEF_REG(
        ft5f, 19,
        name_n32: Some("$fa7"),
        name_n64: Some("$fa7"),
    )
    RABBITIZER_DEF_REG(
        fs0,  20,
        name_n32: Some("$fs0"),
        name_n64: Some("$ft8"),
    )
    RABBITIZER_DEF_REG(
        fs0f, 21,
        name_n32: Some("$ft8"),
        name_n64: Some("$ft9"),
    )
    RABBITIZER_DEF_REG(
        fs1,  22,
        name_n32: Some("$fs1"),
        name_n64: Some("$ft10"),
    )
    RABBITIZER_DEF_REG(
        fs1f, 23,
        name_n32: Some("$ft9"),
        name_n64: Some("$ft11"),
    )
    RABBITIZER_DEF_REG(
        fs2,  24,
        name_n32: Some("$fs2"),
        name_n64: Some("$fs0"),
    )
    RABBITIZER_DEF_REG(
        fs2f, 25,
        name_n32: Some("$ft10"),
        name_n64: Some("$fs1"),
    )
    RABBITIZER_DEF_REG(
        fs3,  26,
        name_n32: Some("$fs3"),
        name_n64: Some("$fs2"),
    )
    RABBITIZER_DEF_REG(
        fs3f, 27,
        name_n32: Some("$ft11"),
        name_n64: Some("$fs3"),
    )
    RABBITIZER_DEF_REG(
        fs4,  28,
        name_n32: Some("$fs4"),
        name_n64: Some("$fs4"),
    )
    RABBITIZER_DEF_REG(
        fs4f, 29,
        name_n32: Some("$ft12"),
        name_n64: Some("$fs5"),
    )
    RABBITIZER_DEF_REG(
        fs5,  30,
        name_n32: Some("$fs5"),
        name_n64: Some("$fs6"),
    )
    RABBITIZER_DEF_REG(
        fs5f, 31,
        name_n32: Some("$ft13"),
        name_n64: Some("$fs7"),
    )
