/* SPDX-FileCopyrightText: © 2022-2024 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    RABBITIZER_DEF_REG(
        R5900_VI,  vi0,  vi0,
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi1,  vi1,
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi2,  vi2,
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi3,  vi3,
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi4,  vi4,
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi5,  vi5,
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi6,  vi6,
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi7,  vi7,
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi8,  vi8,
    )
    RABBITIZER_DEF_REG(
        R5900_VI,  vi9,  vi9,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi10, vi10,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi11, vi11,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi12, vi12,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi13, vi13,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi14, vi14,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi15, vi15,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi16, vi16,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi17, vi17,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi18, vi18,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi19, vi19,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi20, vi20,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi21, vi21,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi22, vi22,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi23, vi23,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi24, vi24,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi25, vi25,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi26, vi26,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi27, vi27,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi28, vi28,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi29, vi29,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi30, vi30,
    )
    RABBITIZER_DEF_REG(
        R5900_VI, vi31, vi31,
    )
