/* SPDX-FileCopyrightText: © 2022-2024 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    RABBITIZER_DEF_REG(
        R5900_VF,  vf0,  vf0,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf1,  vf1,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf2,  vf2,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf3,  vf3,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf4,  vf4,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf5,  vf5,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf6,  vf6,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf7,  vf7,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf8,  vf8,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF,  vf9,  vf9,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf10, vf10,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf11, vf11,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf12, vf12,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf13, vf13,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf14, vf14,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf15, vf15,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf16, vf16,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf17, vf17,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf18, vf18,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf19, vf19,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf20, vf20,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf21, vf21,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf22, vf22,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf23, vf23,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf24, vf24,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf25, vf25,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf26, vf26,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf27, vf27,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf28, vf28,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf29, vf29,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf30, vf30,
        0
    )
    RABBITIZER_DEF_REG(
        R5900_VF, vf31, vf31,
        0
    )
