/* SPDX-FileCopyrightText: © 2022-2024 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    RABBITIZER_DEF_REG(
        COP1_N64, fv0,   f0,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, ft12,  f1,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fv1,   f2,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, ft13,  f3,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, ft0,   f4,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, ft1,   f5,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, ft2,   f6,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, ft3,   f7,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, ft4,   f8,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, ft5,   f9,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, ft6,  f10,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, ft7,  f11,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fa0,  f12,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fa1,  f13,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fa2,  f14,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fa3,  f15,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fa4,  f16,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fa5,  f17,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fa6,  f18,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fa7,  f19,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, ft8,  f20,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, ft9,  f21,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, ft10, f22,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, ft11, f23,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fs0,  f24,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fs1,  f25,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fs2,  f26,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fs3,  f27,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fs4,  f28,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fs5,  f29,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fs6,  f30,
        0
    )
    RABBITIZER_DEF_REG(
        COP1_N64, fs7,  f31,
        0
    )
