/* SPDX-FileCopyrightText: © 2024 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3,  0,  0,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3,  1,  1,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3,  2,  2,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3,  3,  3,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3,  4,  4,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3,  5,  5,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3,  6,  6,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3,  7,  7,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3,  8,  8,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3,  9,  9,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 10, 10,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 11, 11,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 12, 12,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 13, 13,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 14, 14,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 15, 15,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 16, 16,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 17, 17,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 18, 18,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 19, 19,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 20, 20,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 21, 21,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 22, 22,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 23, 23,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 24, 24,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 25, 25,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 26, 26,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 27, 27,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 28, 28,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 29, 29,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 30, 30,
        0
    )
    RABBITIZER_DEF_REG(
        R4000ALLEGREX_COP3, 31, 31,
        0
    )
