/* SPDX-FileCopyrightText: © 2022-2025 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    RABBITIZER_DEF_REG(
        R5900EE_VF,  vf0,  0,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF,  vf1,  1,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF,  vf2,  2,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF,  vf3,  3,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF,  vf4,  4,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF,  vf5,  5,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF,  vf6,  6,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF,  vf7,  7,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF,  vf8,  8,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF,  vf9,  9,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf10, 10,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf11, 11,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf12, 12,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf13, 13,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf14, 14,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf15, 15,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf16, 16,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf17, 17,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf18, 18,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf19, 19,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf20, 20,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf21, 21,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf22, 22,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf23, 23,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf24, 24,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf25, 25,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf26, 26,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf27, 27,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf28, 28,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf29, 29,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf30, 30,
    )
    RABBITIZER_DEF_REG(
        R5900EE_VF, vf31, 31,
    )
