/* SPDX-FileCopyrightText: © 2023-2024 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    // TODO: add here if the category is a handwritten one

    RABBITIZER_DEF_INSTR_ID_TYPE(ALL, INVALID)

    #include "instr_id_types/InstrIdType_cpu.inc"
    #include "instr_id_types/InstrIdType_rsp.inc"
    #include "instr_id_types/InstrIdType_r3000gte.inc"
    #include "instr_id_types/InstrIdType_r4000allegrex.inc"
    #include "instr_id_types/InstrIdType_r5900.inc"
