/* SPDX-FileCopyrightText: © 2023-2024 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    // TODO: add here if the category is a handwritten one

    #include "opcode_categories/opcode_category_core.inc"
    #include "opcode_categories/opcode_category_rsp.inc"
    #include "opcode_categories/opcode_category_r3000gte.inc"
    #include "opcode_categories/opcode_category_r4000allegrex.inc"
    #include "opcode_categories/opcode_category_r5900.inc"
