/* SPDX-FileCopyrightText: © 2023-2025 Decompollaborate */
/* SPDX-License-Identifier: MIT */

    RAB_DEF_OPERAND(ALL, EMPTY, EncodedFieldMask::empty(), ())

    #include "operands/RabbitizerOperandType_core.inc"
    #include "operands/RabbitizerOperandType_rsp.inc"
    #include "operands/RabbitizerOperandType_r3000gte.inc"
    #include "operands/RabbitizerOperandType_r4000allegrex.inc"
    #include "operands/RabbitizerOperandType_r5900.inc"
