/* SPDX-FileCopyrightText: © 2024-2025 Decompollaborate */
/* SPDX-License-Identifier: MIT */

#[cfg(feature = "R5900EE")]
mod common;

#[cfg(feature = "R5900EE")]
use common::{check_test_entries, TestEntry};

#[cfg(feature = "R5900EE")]
use rabbitizer::{
    abi::Abi,
    display_flags::InstructionDisplayFlags,
    instr::{Instruction, InstructionFlags},
    isa::IsaExtension,
    opcodes::Opcode,
    vram::Vram,
};

#[cfg(feature = "R5900EE")]
#[test]
fn check_r5900ee_instructions() {
    const ENTRIES: &[TestEntry] = &[
        TestEntry::new(
            0x4A000038,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vcallms     0x0",
            Opcode::r5900ee_vcallms,
            "vcallms",
            [Some("0x0"), None, None, None, None],
        ),
        TestEntry::new(
            0x4A004038,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vcallms     0x800",
            Opcode::r5900ee_vcallms,
            "vcallms",
            [Some("0x800"), None, None, None, None],
        ),
        TestEntry::new(
            0x4A008038,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vcallms     0x1000",
            Opcode::r5900ee_vcallms,
            "vcallms",
            [Some("0x1000"), None, None, None, None],
        ),
        TestEntry::new(
            0x4A008838,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vcallms     0x1100",
            Opcode::r5900ee_vcallms,
            "vcallms",
            [Some("0x1100"), None, None, None, None],
        ),
        TestEntry::new(
            0x4A009038,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vcallms     0x1200",
            Opcode::r5900ee_vcallms,
            "vcallms",
            [Some("0x1200"), None, None, None, None],
        ),
        TestEntry::new(
            0x4A009838,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vcallms     0x1300",
            Opcode::r5900ee_vcallms,
            "vcallms",
            [Some("0x1300"), None, None, None, None],
        ),
        TestEntry::new(
            0x4A00A038,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vcallms     0x1400",
            Opcode::r5900ee_vcallms,
            "vcallms",
            [Some("0x1400"), None, None, None, None],
        ),
        TestEntry::new(
            0x4A07FFF8,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vcallms     0xFFF8",
            Opcode::r5900ee_vcallms,
            "vcallms",
            [Some("0xFFF8"), None, None, None, None],
        ),
        TestEntry::new(
            0x4A080038,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vcallms     0x10000",
            Opcode::r5900ee_vcallms,
            "vcallms",
            [Some("0x10000"), None, None, None, None],
        ),
        TestEntry::new(
            0x4A1F8038,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vcallms     0x3F000",
            Opcode::r5900ee_vcallms,
            "vcallms",
            [Some("0x3F000"), None, None, None, None],
        ),
        TestEntry::new(
            0x4A1FFFB8,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vcallms     0x3FFF0",
            Opcode::r5900ee_vcallms,
            "vcallms",
            [Some("0x3FFF0"), None, None, None, None],
        ),
        TestEntry::new(
            0x4A1FFFF8,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vcallms     0x3FFF8",
            Opcode::r5900ee_vcallms,
            "vcallms",
            [Some("0x3FFF8"), None, None, None, None],
        ),
        TestEntry::new(
            0x70001030,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "pmfhl.lw    $v0",
            Opcode::r5900ee_pmfhl_lw,
            "pmfhl.lw",
            [Some("$v0"), None, None, None, None],
        ),
        TestEntry::new(
            0x70001070,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "pmfhl.uw    $v0",
            Opcode::r5900ee_pmfhl_uw,
            "pmfhl.uw",
            [Some("$v0"), None, None, None, None],
        ),
        TestEntry::new(
            0x700010B0,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "pmfhl.slw   $v0",
            Opcode::r5900ee_pmfhl_slw,
            "pmfhl.slw",
            [Some("$v0"), None, None, None, None],
        ),
        TestEntry::new(
            0x700010F0,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "pmfhl.lh    $v0",
            Opcode::r5900ee_pmfhl_lh,
            "pmfhl.lh",
            [Some("$v0"), None, None, None, None],
        ),
        TestEntry::new(
            0x70001130,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "pmfhl.sh    $v0",
            Opcode::r5900ee_pmfhl_sh,
            "pmfhl.sh",
            [Some("$v0"), None, None, None, None],
        ),
        TestEntry::new(
            0x70000031,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "pmthl.lw    $zero",
            Opcode::r5900ee_pmthl_lw,
            "pmthl.lw",
            [Some("$zero"), None, None, None, None],
        ),
        TestEntry::new(
            0x4B020BFE,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vilwr.x     $vi2, ($vi1)",
            Opcode::r5900ee_vilwr_x,
            "vilwr.x",
            [Some("$vi2"), Some("($vi1)"), None, None, None],
        ),
        TestEntry::new(
            0x4A820BFE,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vilwr.y     $vi2, ($vi1)",
            Opcode::r5900ee_vilwr_y,
            "vilwr.y",
            [Some("$vi2"), Some("($vi1)"), None, None, None],
        ),
        TestEntry::new(
            0x4A420BFE,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vilwr.z     $vi2, ($vi1)",
            Opcode::r5900ee_vilwr_z,
            "vilwr.z",
            [Some("$vi2"), Some("($vi1)"), None, None, None],
        ),
        TestEntry::new(
            0x4A220BFE,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vilwr.w     $vi2, ($vi1)",
            Opcode::r5900ee_vilwr_w,
            "vilwr.w",
            [Some("$vi2"), Some("($vi1)"), None, None, None],
        ),
        TestEntry::new(
            0x4B020BFF,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "viswr.x     $vi2, ($vi1)",
            Opcode::r5900ee_viswr_x,
            "viswr.x",
            [Some("$vi2"), Some("($vi1)"), None, None, None],
        ),
        TestEntry::new(
            0x4A820BFF,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "viswr.y     $vi2, ($vi1)",
            Opcode::r5900ee_viswr_y,
            "viswr.y",
            [Some("$vi2"), Some("($vi1)"), None, None, None],
        ),
        TestEntry::new(
            0x4A420BFF,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "viswr.z     $vi2, ($vi1)",
            Opcode::r5900ee_viswr_z,
            "viswr.z",
            [Some("$vi2"), Some("($vi1)"), None, None, None],
        ),
        TestEntry::new(
            0x4A220BFF,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "viswr.w     $vi2, ($vi1)",
            Opcode::r5900ee_viswr_w,
            "viswr.w",
            [Some("$vi2"), Some("($vi1)"), None, None, None],
        ),
        TestEntry::new(
            0x70111334,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "psllh       $v0, $s1, 12",
            Opcode::r5900ee_psllh,
            "psllh",
            [Some("$v0"), Some("$s1"), Some("12"), None, None],
        ),
        TestEntry::new(
            0x70111336,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "psrlh       $v0, $s1, 12",
            Opcode::r5900ee_psrlh,
            "psrlh",
            [Some("$v0"), Some("$s1"), Some("12"), None, None],
        ),
        TestEntry::new(
            0x70111337,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "psrah       $v0, $s1, 12",
            Opcode::r5900ee_psrah,
            "psrah",
            [Some("$v0"), Some("$s1"), Some("12"), None, None],
        ),
        TestEntry::new(
            0x7011133C,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "psllw       $v0, $s1, 12",
            Opcode::r5900ee_psllw,
            "psllw",
            [Some("$v0"), Some("$s1"), Some("12"), None, None],
        ),
        TestEntry::new(
            0x7011133E,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "psrlw       $v0, $s1, 12",
            Opcode::r5900ee_psrlw,
            "psrlw",
            [Some("$v0"), Some("$s1"), Some("12"), None, None],
        ),
        TestEntry::new(
            0x7011133F,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "psraw       $v0, $s1, 12",
            Opcode::r5900ee_psraw,
            "psraw",
            [Some("$v0"), Some("$s1"), Some("12"), None, None],
        ),
        TestEntry {
            instr: Instruction::new(
                0x4A00551D,
                Vram::new(0x80000000),
                InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            ),
            imm_override: None,
            display_flags: InstructionDisplayFlags::new_gnu_as(),
            valid: true,
            expected: "vmaxi       $vf20, $vf10, $I",
            expected_opcode: Opcode::r5900ee_vmaxi,
            opcode_str: "vmaxi",
            operands_str: [Some("$vf20"), Some("$vf10"), Some("$I"), None, None],
            test_encoder: true,
        },
        TestEntry {
            instr: Instruction::new(
                0x4A00551D,
                Vram::new(0x80000000),
                InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            ),
            imm_override: None,
            display_flags: InstructionDisplayFlags::new_legacy_as(),
            valid: true,
            expected: "vmaxi       $vf20, $vf10, I",
            expected_opcode: Opcode::r5900ee_vmaxi,
            opcode_str: "vmaxi",
            operands_str: [Some("$vf20"), Some("$vf10"), Some("I"), None, None],
            test_encoder: true,
        },
        TestEntry {
            instr: Instruction::new(
                0x4A00551C,
                Vram::new(0x80000000),
                InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            ),
            imm_override: None,
            display_flags: InstructionDisplayFlags::new_gnu_as(),
            valid: true,
            expected: "vmulq       $vf20, $vf10, $Q",
            expected_opcode: Opcode::r5900ee_vmulq,
            opcode_str: "vmulq",
            operands_str: [Some("$vf20"), Some("$vf10"), Some("$Q"), None, None],
            test_encoder: true,
        },
        TestEntry {
            instr: Instruction::new(
                0x4A00551C,
                Vram::new(0x80000000),
                InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            ),
            imm_override: None,
            display_flags: InstructionDisplayFlags::new_legacy_as(),
            valid: true,
            expected: "vmulq       $vf20, $vf10, Q",
            expected_opcode: Opcode::r5900ee_vmulq,
            opcode_str: "vmulq",
            operands_str: [Some("$vf20"), Some("$vf10"), Some("Q"), None, None],
            test_encoder: true,
        },
        TestEntry {
            instr: Instruction::new(
                0x4A06043C,
                Vram::new(0x80000000),
                InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            ),
            imm_override: None,
            display_flags: InstructionDisplayFlags::new_gnu_as(),
            valid: true,
            expected: "vrnext      $vf6, $R",
            expected_opcode: Opcode::r5900ee_vrnext,
            opcode_str: "vrnext",
            operands_str: [Some("$vf6"), Some("$R"), None, None, None],
            test_encoder: true,
        },
        TestEntry {
            instr: Instruction::new(
                0x4A06043C,
                Vram::new(0x80000000),
                InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            ),
            imm_override: None,
            display_flags: InstructionDisplayFlags::new_legacy_as(),
            valid: true,
            expected: "vrnext      $vf6, R",
            expected_opcode: Opcode::r5900ee_vrnext,
            opcode_str: "vrnext",
            operands_str: [Some("$vf6"), Some("R"), None, None, None],
            test_encoder: true,
        },
        TestEntry {
            instr: Instruction::new(
                0x4A06003C,
                Vram::new(0x80000000),
                InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            ),
            imm_override: None,
            display_flags: InstructionDisplayFlags::new_gnu_as(),
            valid: true,
            expected: "vaddax      $ACC, $vf0, $vf6x",
            expected_opcode: Opcode::r5900ee_vaddax,
            opcode_str: "vaddax",
            operands_str: [Some("$ACC"), Some("$vf0"), Some("$vf6x"), None, None],
            test_encoder: true,
        },
        TestEntry {
            instr: Instruction::new(
                0x4A06003C,
                Vram::new(0x80000000),
                InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            ),
            imm_override: None,
            display_flags: InstructionDisplayFlags::new_legacy_as(),
            valid: true,
            expected: "vaddax      ACC, $vf0, $vf6x",
            expected_opcode: Opcode::r5900ee_vaddax,
            opcode_str: "vaddax",
            operands_str: [Some("ACC"), Some("$vf0"), Some("$vf6x"), None, None],
            test_encoder: true,
        },
        TestEntry::new(
            0x4A0663BC,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vdiv        Q, $vf12x, $vf6x",
            Opcode::r5900ee_vdiv,
            "vdiv",
            [Some("Q"), Some("$vf12x"), Some("$vf6x"), None, None],
        ),
        TestEntry::new(
            0x4A066630,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "viadd       $vi24, $vi12, $vi6",
            Opcode::r5900ee_viadd,
            "viadd",
            [Some("$vi24"), Some("$vi12"), Some("$vi6"), None, None],
        ),
        TestEntry::new(
            0x4A066632,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "viaddi      $vi6, $vi12, -0x8",
            Opcode::r5900ee_viaddi,
            "viaddi",
            [Some("$vi6"), Some("$vi12"), Some("-0x8"), None, None],
        ),
        TestEntry::new(
            0x4A06637E,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vlqd        $vf6, (--$vi12)",
            Opcode::r5900ee_vlqd,
            "vlqd",
            [Some("$vf6"), Some("(--$vi12)"), None, None, None],
        ),
        TestEntry::new(
            0x4A06637F,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vsqd        $vf12, (--$vi6)",
            Opcode::r5900ee_vsqd,
            "vsqd",
            [Some("$vf12"), Some("(--$vi6)"), None, None, None],
        ),
        TestEntry::new(
            0x4A06637C,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vlqi        $vf6, ($vi12++)",
            Opcode::r5900ee_vlqi,
            "vlqi",
            [Some("$vf6"), Some("($vi12++)"), None, None, None],
        ),
        TestEntry::new(
            0x4A06637D,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "vsqi        $vf12, ($vi6++)",
            Opcode::r5900ee_vsqi,
            "vsqi",
            [Some("$vf12"), Some("($vi6++)"), None, None, None],
        ),
        TestEntry::new(
            0x4A0307B2,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "viaddi      $vi3, $vi0, -0x2",
            Opcode::r5900ee_viaddi,
            "viaddi",
            [Some("$vi3"), Some("$vi0"), Some("-0x2"), None, None],
        ),
        TestEntry::new(
            0x4A0303B2,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "viaddi      $vi3, $vi0, 0xE",
            Opcode::r5900ee_viaddi,
            "viaddi",
            [Some("$vi3"), Some("$vi0"), Some("0xE"), None, None],
        ),
        TestEntry::new(
            0x48300800,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "qmfc2.ni    $s0, $vf1",
            Opcode::r5900ee_qmfc2_ni,
            "qmfc2.ni",
            [Some("$s0"), Some("$vf1"), None, None, None],
        ),
        TestEntry::new(
            0x48300801,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "qmfc2.i     $s0, $vf1",
            Opcode::r5900ee_qmfc2_i,
            "qmfc2.i",
            [Some("$s0"), Some("$vf1"), None, None, None],
        ),
        TestEntry::new(
            0x48500800,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "cfc2.ni     $s0, $vi1",
            Opcode::r5900ee_cfc2_ni,
            "cfc2.ni",
            [Some("$s0"), Some("$vi1"), None, None, None],
        ),
        TestEntry::new(
            0x48500801,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "cfc2.i      $s0, $vi1",
            Opcode::r5900ee_cfc2_i,
            "cfc2.i",
            [Some("$s0"), Some("$vi1"), None, None, None],
        ),
        TestEntry::new(
            0x48B00800,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "qmtc2.ni    $s0, $vf1",
            Opcode::r5900ee_qmtc2_ni,
            "qmtc2.ni",
            [Some("$s0"), Some("$vf1"), None, None, None],
        ),
        TestEntry::new(
            0x48B00801,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "qmtc2.i     $s0, $vf1",
            Opcode::r5900ee_qmtc2_i,
            "qmtc2.i",
            [Some("$s0"), Some("$vf1"), None, None, None],
        ),
        TestEntry::new(
            0x48D00800,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "ctc2.ni     $s0, $vi1",
            Opcode::r5900ee_ctc2_ni,
            "ctc2.ni",
            [Some("$s0"), Some("$vi1"), None, None, None],
        ),
        TestEntry::new(
            0x48D00801,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "ctc2.i      $s0, $vi1",
            Opcode::r5900ee_ctc2_i,
            "ctc2.i",
            [Some("$s0"), Some("$vi1"), None, None, None],
        ),
        TestEntry::new(
            0xD8771234,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "lqc2        $vf23, 0x1234($v1)",
            Opcode::r5900ee_lqc2,
            "lqc2",
            [Some("$vf23"), Some("0x1234($v1)"), None, None, None],
        ),
        TestEntry::new(
            0xF8661234,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "sqc2        $vf6, 0x1234($v1)",
            Opcode::r5900ee_sqc2,
            "sqc2",
            [Some("$vf6"), Some("0x1234($v1)"), None, None, None],
        ),
        TestEntry::new(
            0x78771234,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "lq          $s7, 0x1234($v1)",
            Opcode::r5900ee_lq,
            "lq",
            [Some("$s7"), Some("0x1234($v1)"), None, None, None],
        ),
        TestEntry::new(
            0x7C661234,
            InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64),
            "sq          $a2, 0x1234($v1)",
            Opcode::r5900ee_sq,
            "sq",
            [Some("$a2"), Some("0x1234($v1)"), None, None, None],
        ),
    ];

    assert_eq!(check_test_entries(ENTRIES), (0, 0));
}

#[cfg(feature = "R5900EE")]
#[test]
fn check_r5900ee_trunc_cvt_instructions() {
    const ENTRIES: &[TestEntry] = &[
        TestEntry {
            instr: Instruction::new(0x4600600D, Vram::new(0x80000000), InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64)),
            imm_override: None,
            display_flags: InstructionDisplayFlags::new_gnu_as(),
            valid: true,
            expected: ".word       0x4600600D                   /* trunc.w.s   $fv0, $fa0 / 00000000 <OpcodeCategory: CORE_COP1_FPUS> */",
            expected_opcode: Opcode::core_trunc_w_s,
            opcode_str: "trunc.w.s",
            operands_str: [Some("$fv0"), Some("$fa0"), None, None, None],
            test_encoder: true,
        },
        TestEntry {
            instr: Instruction::new(0x46006024, Vram::new(0x80000000), InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64)),
            imm_override: None,
            display_flags: InstructionDisplayFlags::new_gnu_as(),
            valid: true,
            expected: ".word       0x46006024                   /* cvt.w.s     $fv0, $fa0 / 00000000 <OpcodeCategory: CORE_COP1_FPUS> */",
            expected_opcode: Opcode::core_cvt_w_s,
            opcode_str: "cvt.w.s",
            operands_str: [Some("$fv0"), Some("$fa0"), None, None, None],
            test_encoder: true,
        },
        TestEntry {
            instr: Instruction::new(0x4600600D, Vram::new(0x80000000), InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64)),
            imm_override: None,
            display_flags: InstructionDisplayFlags::new_legacy_as(),
            valid: true,
            expected: "trunc.w.s   $f0, $f12",
            expected_opcode: Opcode::core_trunc_w_s,
            opcode_str: "trunc.w.s",
            operands_str: [Some("$f0"), Some("$f12"), None, None, None],
            test_encoder: true,
        },
        TestEntry {
            instr: Instruction::new(0x46006024, Vram::new(0x80000000), InstructionFlags::new_extension(IsaExtension::R5900EE).with_abi(Abi::EABI64)),
            imm_override: None,
            display_flags: InstructionDisplayFlags::new_legacy_as(),
            valid: true,
            expected: "cvt.w.s     $f0, $f12",
            expected_opcode: Opcode::core_cvt_w_s,
            opcode_str: "cvt.w.s",
            operands_str: [Some("$f0"), Some("$f12"), None, None, None],
            test_encoder: true,
        },
    ];

    assert_eq!(check_test_entries(ENTRIES), (0, 0));
}
