name: Build Python package in isolated environment

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
  buildstuff:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y python3-venv

      - name: Setup venv
        run: python3 -m venv .venv

      - name: Install build module
        run: |
          . .venv/bin/activate
          python3 -m pip install build -U

      - name: Build
        run: |
          . .venv/bin/activate
          python3 -m build
