name: Lint markdown files

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
  checks:
    name: Lint md files
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint markdown files
        uses: articulate/actions-markdownlint@v1.1.0
        with:
          config: .markdownlint.jsonc
