# Based on https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml
# Permalink: https://github.com/pypa/cibuildwheel/blob/9c75ea15c2f31a77e6043b80b1b7081372319d85/examples/github-deploy.yml

name: Build and upload to PyPI

# Only run on releases
# on:
#   push:
#     # Pattern matched against refs/tags
#     tags:
#       - '**'           # Push events to every tag including hierarchical tags like v1.0/beta
on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]

    steps:
      - name: Checkout reposistory
        uses: actions/checkout@main

      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: '3.9 - 3.13'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS_WINDOWS: "auto"
          CIBW_ARCHS_LINUX: "auto"
          CIBW_ARCHS_MACOS: "all"

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@main

      - name: Build sdist
        run: pipx run build --sdist

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-22.04
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@main
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
