name: Python unit tests

on:
  push:
  pull_request:

jobs:
  unit_tests:
    name: Python ${{ matrix.py_version }} unit tests on '${{ matrix.os.name }}'
    runs-on: ${{ matrix.os.runner }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          {
            name: linux,
            runner: ubuntu-22.04,
            python_venv_activate: source .venv/bin/activate,
            find_wheel_cmd: find ./dist/ -name "rabbitizer-*.whl"
          },
          {
            name: macos-arm,
            runner: macos-latest,
            python_venv_activate: source .venv/bin/activate,
            find_wheel_cmd: find ./dist/ -name "rabbitizer-*.whl"
          },
          {
            name: macos-intel,
            runner: macos-15-intel,
            python_venv_activate: source .venv/bin/activate,
            find_wheel_cmd: find ./dist/ -name "rabbitizer-*.whl"
          },
          {
            name: windows,
            runner: windows-latest,
            python_venv_activate: .venv\Scripts\Activate.ps1,
            find_wheel_cmd: Get-ChildItem -Path .\dist\ -Recurse -Filter "rabbitizer-*.whl"
          },
        ]
        py_version:
          - '3.4'
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
          - '3.14t'

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Print Python version
        run: |
          python3 --version

      - name: Set up Python ${{ matrix.py_version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py_version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Setup Python venv
        run: |
          python3 --version
          uv venv .venv --no-config -p ${{ matrix.py_version }}
          ${{ matrix.os.python_venv_activate }}
          python3 --version

      - name: Build wheel
        run: |
          ${{ matrix.os.python_venv_activate }}
          uv build --wheel

      - name: Install wheel
        run: |
          ${{ matrix.os.python_venv_activate }}
          ${{ matrix.os.find_wheel_cmd }}
          uv pip install --force-reinstall $(${{ matrix.os.find_wheel_cmd }})

      - name: Run the test
        run: |
          ${{ matrix.os.python_venv_activate }}
          where python3
          python3 -c "import sys; print(sys.executable)"
          python3 tests/python/disasm_test.py
