#!/usr/bin/env python3

# SPDX-FileCopyrightText: © 2022 Decompollaborate
# SPDX-License-Identifier: MIT

from __future__ import annotations

from .Enum import Enum


class InstrId:
    cpu_INVALID: Enum
    cpu_mthi: Enum
    cpu_mtlo: Enum
    cpu_jr: Enum
    cpu_jalr: Enum
    cpu_jalr_rd: Enum
    cpu_mfhi: Enum
    cpu_mflo: Enum
    cpu_mult: Enum
    cpu_multu: Enum
    cpu_dmult: Enum
    cpu_dmultu: Enum
    cpu_tge: Enum
    cpu_tgeu: Enum
    cpu_tlt: Enum
    cpu_tltu: Enum
    cpu_teq: Enum
    cpu_tne: Enum
    cpu_movz: Enum
    cpu_movn: Enum
    cpu_div: Enum
    cpu_divu: Enum
    cpu_sn64_div: Enum
    cpu_sn64_divu: Enum
    cpu_ddiv: Enum
    cpu_ddivu: Enum
    cpu_add: Enum
    cpu_addu: Enum
    cpu_sub: Enum
    cpu_subu: Enum
    cpu_and: Enum
    cpu_or: Enum
    cpu_xor: Enum
    cpu_nor: Enum
    cpu_slt: Enum
    cpu_sltu: Enum
    cpu_dadd: Enum
    cpu_daddu: Enum
    cpu_dsub: Enum
    cpu_dsubu: Enum
    cpu_syscall: Enum
    cpu_break: Enum
    cpu_sync: Enum
    cpu_dsllv: Enum
    cpu_dsrlv: Enum
    cpu_dsrav: Enum
    cpu_sllv: Enum
    cpu_srlv: Enum
    cpu_srav: Enum
    cpu_sll: Enum
    cpu_srl: Enum
    cpu_sra: Enum
    cpu_dsll: Enum
    cpu_dsrl: Enum
    cpu_dsra: Enum
    cpu_dsll32: Enum
    cpu_dsrl32: Enum
    cpu_dsra32: Enum
    cpu_bltz: Enum
    cpu_bgez: Enum
    cpu_bltzl: Enum
    cpu_bgezl: Enum
    cpu_tgei: Enum
    cpu_tgeiu: Enum
    cpu_tlti: Enum
    cpu_tltiu: Enum
    cpu_bltzal: Enum
    cpu_bgezal: Enum
    cpu_bltzall: Enum
    cpu_bgezall: Enum
    cpu_teqi: Enum
    cpu_tnei: Enum
    cpu_j: Enum
    cpu_jal: Enum
    cpu_beq: Enum
    cpu_bne: Enum
    cpu_beql: Enum
    cpu_bnel: Enum
    cpu_blez: Enum
    cpu_bgtz: Enum
    cpu_blezl: Enum
    cpu_bgtzl: Enum
    cpu_lui: Enum
    cpu_andi: Enum
    cpu_ori: Enum
    cpu_xori: Enum
    cpu_addi: Enum
    cpu_addiu: Enum
    cpu_daddi: Enum
    cpu_daddiu: Enum
    cpu_slti: Enum
    cpu_sltiu: Enum
    cpu_ldl: Enum
    cpu_ldr: Enum
    cpu_lb: Enum
    cpu_lh: Enum
    cpu_lwl: Enum
    cpu_lw: Enum
    cpu_lbu: Enum
    cpu_lhu: Enum
    cpu_lwr: Enum
    cpu_lwu: Enum
    cpu_sb: Enum
    cpu_sh: Enum
    cpu_swl: Enum
    cpu_sw: Enum
    cpu_sdl: Enum
    cpu_sdr: Enum
    cpu_swr: Enum
    cpu_ll: Enum
    cpu_pref: Enum
    cpu_lld: Enum
    cpu_ld: Enum
    cpu_sc: Enum
    cpu_scd: Enum
    cpu_sd: Enum
    cpu_lwc1: Enum
    cpu_ldc1: Enum
    cpu_swc1: Enum
    cpu_sdc1: Enum
    cpu_lwc2: Enum
    cpu_ldc2: Enum
    cpu_swc2: Enum
    cpu_sdc2: Enum
    cpu_mfc0: Enum
    cpu_dmfc0: Enum
    cpu_cfc0: Enum
    cpu_mtc0: Enum
    cpu_dmtc0: Enum
    cpu_ctc0: Enum
    cpu_tlbr: Enum
    cpu_tlbwi: Enum
    cpu_tlbwr: Enum
    cpu_tlbp: Enum
    cpu_eret: Enum
    cpu_bc0t: Enum
    cpu_bc0f: Enum
    cpu_bc0tl: Enum
    cpu_bc0fl: Enum
    cpu_mfc1: Enum
    cpu_dmfc1: Enum
    cpu_mtc1: Enum
    cpu_dmtc1: Enum
    cpu_cfc1: Enum
    cpu_ctc1: Enum
    cpu_bc1f: Enum
    cpu_bc1t: Enum
    cpu_bc1fl: Enum
    cpu_bc1tl: Enum
    cpu_add_s: Enum
    cpu_sub_s: Enum
    cpu_mul_s: Enum
    cpu_div_s: Enum
    cpu_add_d: Enum
    cpu_sub_d: Enum
    cpu_mul_d: Enum
    cpu_div_d: Enum
    cpu_sqrt_s: Enum
    cpu_abs_s: Enum
    cpu_mov_s: Enum
    cpu_neg_s: Enum
    cpu_sqrt_d: Enum
    cpu_abs_d: Enum
    cpu_mov_d: Enum
    cpu_neg_d: Enum
    cpu_round_l_s: Enum
    cpu_trunc_l_s: Enum
    cpu_ceil_l_s: Enum
    cpu_floor_l_s: Enum
    cpu_round_l_d: Enum
    cpu_trunc_l_d: Enum
    cpu_ceil_l_d: Enum
    cpu_floor_l_d: Enum
    cpu_round_w_s: Enum
    cpu_trunc_w_s: Enum
    cpu_ceil_w_s: Enum
    cpu_floor_w_s: Enum
    cpu_round_w_d: Enum
    cpu_trunc_w_d: Enum
    cpu_ceil_w_d: Enum
    cpu_floor_w_d: Enum
    cpu_c_f_s: Enum
    cpu_c_un_s: Enum
    cpu_c_eq_s: Enum
    cpu_c_ueq_s: Enum
    cpu_c_olt_s: Enum
    cpu_c_ult_s: Enum
    cpu_c_ole_s: Enum
    cpu_c_ule_s: Enum
    cpu_c_f_d: Enum
    cpu_c_un_d: Enum
    cpu_c_eq_d: Enum
    cpu_c_ueq_d: Enum
    cpu_c_olt_d: Enum
    cpu_c_ult_d: Enum
    cpu_c_ole_d: Enum
    cpu_c_ule_d: Enum
    cpu_c_sf_s: Enum
    cpu_c_ngle_s: Enum
    cpu_c_seq_s: Enum
    cpu_c_ngl_s: Enum
    cpu_c_lt_s: Enum
    cpu_c_nge_s: Enum
    cpu_c_le_s: Enum
    cpu_c_ngt_s: Enum
    cpu_c_sf_d: Enum
    cpu_c_ngle_d: Enum
    cpu_c_seq_d: Enum
    cpu_c_ngl_d: Enum
    cpu_c_lt_d: Enum
    cpu_c_nge_d: Enum
    cpu_c_le_d: Enum
    cpu_c_ngt_d: Enum
    cpu_cvt_s_d: Enum
    cpu_cvt_s_w: Enum
    cpu_cvt_s_l: Enum
    cpu_cvt_d_s: Enum
    cpu_cvt_d_w: Enum
    cpu_cvt_d_l: Enum
    cpu_cvt_w_s: Enum
    cpu_cvt_w_d: Enum
    cpu_cvt_l_s: Enum
    cpu_cvt_l_d: Enum
    cpu_nop: Enum
    cpu_beqz: Enum
    cpu_bnez: Enum
    cpu_b: Enum
    cpu_move: Enum
    cpu_not: Enum
    cpu_negu: Enum
    cpu_MAX: Enum

    rsp_INVALID: Enum
    rsp_vmulf: Enum
    rsp_vmulu: Enum
    rsp_vrndp: Enum
    rsp_vmulq: Enum
    rsp_vmudl: Enum
    rsp_vmudm: Enum
    rsp_vmudn: Enum
    rsp_vmudh: Enum
    rsp_vmacf: Enum
    rsp_vmacu: Enum
    rsp_vrndn: Enum
    rsp_vmacq: Enum
    rsp_vmadl: Enum
    rsp_vmadm: Enum
    rsp_vmadn: Enum
    rsp_vmadh: Enum
    rsp_vadd: Enum
    rsp_vsub: Enum
    rsp_vabs: Enum
    rsp_vaddc: Enum
    rsp_vsubc: Enum
    rsp_vsar: Enum
    rsp_vand: Enum
    rsp_vnand: Enum
    rsp_vor: Enum
    rsp_vnor: Enum
    rsp_vxor: Enum
    rsp_vnxor: Enum
    rsp_vlt: Enum
    rsp_veq: Enum
    rsp_vne: Enum
    rsp_vge: Enum
    rsp_vcl: Enum
    rsp_vch: Enum
    rsp_vcr: Enum
    rsp_vmrg: Enum
    rsp_vrcp: Enum
    rsp_vrcpl: Enum
    rsp_vrcph: Enum
    rsp_vmov: Enum
    rsp_vrsq: Enum
    rsp_vrsql: Enum
    rsp_vrsqh: Enum
    rsp_vnop: Enum
    rsp_mfc2: Enum
    rsp_mtc2: Enum
    rsp_cfc2: Enum
    rsp_ctc2: Enum
    rsp_sbv: Enum
    rsp_ssv: Enum
    rsp_slv: Enum
    rsp_sdv: Enum
    rsp_sqv: Enum
    rsp_srv: Enum
    rsp_spv: Enum
    rsp_suv: Enum
    rsp_swv: Enum
    rsp_shv: Enum
    rsp_sfv: Enum
    rsp_stv: Enum
    rsp_lbv: Enum
    rsp_lsv: Enum
    rsp_llv: Enum
    rsp_ldv: Enum
    rsp_lqv: Enum
    rsp_lrv: Enum
    rsp_lpv: Enum
    rsp_luv: Enum
    rsp_lhv: Enum
    rsp_lfv: Enum
    rsp_ltv: Enum
    rsp_jr: Enum
    rsp_jalr: Enum
    rsp_jalr_rd: Enum
    rsp_movz: Enum
    rsp_movn: Enum
    rsp_add: Enum
    rsp_addu: Enum
    rsp_sub: Enum
    rsp_subu: Enum
    rsp_and: Enum
    rsp_or: Enum
    rsp_xor: Enum
    rsp_nor: Enum
    rsp_slt: Enum
    rsp_sltu: Enum
    rsp_break: Enum
    rsp_sllv: Enum
    rsp_srlv: Enum
    rsp_srav: Enum
    rsp_sll: Enum
    rsp_srl: Enum
    rsp_sra: Enum
    rsp_bltz: Enum
    rsp_bgez: Enum
    rsp_bltzal: Enum
    rsp_bgezal: Enum
    rsp_j: Enum
    rsp_jal: Enum
    rsp_beq: Enum
    rsp_bne: Enum
    rsp_blez: Enum
    rsp_bgtz: Enum
    rsp_lui: Enum
    rsp_andi: Enum
    rsp_ori: Enum
    rsp_xori: Enum
    rsp_addi: Enum
    rsp_addiu: Enum
    rsp_slti: Enum
    rsp_sltiu: Enum
    rsp_lb: Enum
    rsp_lh: Enum
    rsp_lw: Enum
    rsp_lbu: Enum
    rsp_lhu: Enum
    rsp_sb: Enum
    rsp_sh: Enum
    rsp_sw: Enum
    rsp_pref: Enum
    rsp_lwc1: Enum
    rsp_swc1: Enum
    rsp_mfc0: Enum
    rsp_mtc0: Enum
    rsp_nop: Enum
    rsp_beqz: Enum
    rsp_bnez: Enum
    rsp_b: Enum
    rsp_move: Enum
    rsp_not: Enum
    rsp_negu: Enum
    rsp_MAX: Enum

    ALL_MAX: Enum
